apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petstore-certificate
  namespace: dev
spec:
  dnsNames:
    - vatsfamily.ca
  secretName: petstore-certificate-secret
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer